# ML Project 6033657523 - Cleaning Data

## Importing the libraries

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [0]:
dataset = pd.read_csv('data.csv')
dataset.head(10)

         SKU        date  PrevAVGCost  ...  LatestDateCost  Type  GenPrice
0  A-A-00001  2019-01-04    27.919192  ...       20.535354     A      41.0
1  A-B-00001  2019-01-04    57.333333  ...       61.838384     A      92.0
2  A-B-00002  2019-01-04    50.777778  ...       50.000000     A      76.0
3  A-C-00001  2019-01-04    45.747475  ...       38.080808     B      75.0
4  A-C-00019  2019-01-04    45.747475  ...       38.080808     B      75.0
5  A-C-00007  2019-01-04    59.373737  ...       58.272727     B      90.0
6  A-C-00002  2019-01-04    39.777778  ...       39.313131     B      68.0
7  A-C-00010  2019-01-04    61.222222  ...        0.000000     B      99.0
8  A-C-00003  2019-01-04    39.232323  ...       39.707071     B      64.0
9  A-C-00021  2019-01-04    48.818182  ...       49.242424     B      75.0

[10 rows x 8 columns]

In [0]:
dataset.shape

In [0]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25116 entries, 0 to 25115
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SKU               25116 non-null  object
 1   date              25116 non-null  object
 2   PrevAVGCost       24639 non-null  float64
 3   PrevAssignedCost  24639 non-null  float64
 4   AVGCost           24639 non-null  float64
 5   LatestDateCost    24639 non-null  float64
 6   Type              24802 non-null  object
 7   GenPrice          24639 non-null  float64
dtypes: float64(5), object(3)
memory usage: 1.5+ MB

In [0]:
pd.options.display.float_format = "{:.2f}".format
dataset.describe()

       PrevAVGCost  PrevAssignedCost  AVGCost  LatestDateCost    GenPrice
count     24639.00          24639.00 24639.00        24639.00    24639.00
mean         38.08            475.10    38.06           36.42      603.42
std          55.12          64343.91    54.72           51.95    80429.86
min           0.00              0.00     0.00            0.00        2.00
25%           0.00             23.00     0.00            0.00       35.00
50%          23.64             43.00    23.79           22.42       64.00
75%          51.88             78.00    51.96           50.85      112.00
max        1054.34       10100002.00  1054.34          784.32 12625006.00

## Taking care of missing and excess data

### Remove missing GenPrice and GenPrice = 0

In [0]:
dataset[(dataset['GenPrice'].isnull()) | (dataset['GenPrice'] == 0)]

             SKU        date  PrevAVGCost  ...  LatestDateCost  Type  GenPrice
11     A-C-00006  2019-01-04          nan  ...             nan     A       nan
77     A-A-00013  2019-01-04          nan  ...             nan     A       nan
303    E-A-00195  2019-01-04          nan  ...             nan     G       nan
317    E-A-00399  2019-01-04          nan  ...             nan     G       nan
455    E-A-00023  2019-01-04          nan  ...             nan     G       nan
...          ...         ...          ...  ...             ...   ...       ...
25111  A-E-00170  2020-01-13          nan  ...             nan   NaN       nan
25112  A-E-00171  2020-01-13          nan  ...             nan   NaN       nan
25113  A-D-00149  2020-01-13          nan  ...             nan   NaN       nan
25114  A-B-00040  2020-01-13          nan  ...             nan   NaN       nan
25115  A-I-00090  2020-01-13          nan  ...             nan   NaN       nan

[477 rows x 8 columns]

In [0]:
dataset.drop(dataset[(dataset['GenPrice'].isnull()) | (dataset['GenPrice'] == 0)].index, inplace = True )
dataset.shape

(24639, 8)

### Remove PrevAssignedCost = 0 and AVGCost = 0

In [0]:
dataset[(dataset['PrevAssignedCost'] == 0) & (dataset['AVGCost'] == 0)]

             SKU        date  PrevAVGCost  ...  LatestDateCost  Type  GenPrice
4071   E-E-00084  2019-02-25         0.00  ...            0.00     G    163.00
4817   A-E-00092  2019-03-12         0.00  ...            0.00     A     36.00
5327   A-E-00092  2019-03-20         0.00  ...            0.00     A     36.00
6875   A-E-00092  2019-04-10         0.00  ...            0.00     A     36.00
7393   A-E-00092  2019-04-22         0.00  ...            0.00     A     36.00
7911   A-E-00092  2019-04-26         0.00  ...            0.00     A     36.00
11455  A-E-00092  2019-06-19         0.00  ...            0.00     A     35.00
12934  A-E-00092  2019-07-11         0.00  ...            0.00     A     35.00
13427  A-E-00092  2019-07-22         0.00  ...            0.00     A     35.00
13920  A-E-00092  2019-07-25         0.00  ...            0.00     A     35.00
14413  A-E-00092  2019-08-05         0.00  ...            0.00     A     33.00

[11 rows x 8 columns]

In [0]:
dataset.drop(dataset[(dataset['PrevAssignedCost'] == 0) & (dataset['AVGCost'] == 0)].index, inplace = True)
dataset.shape

(24628, 8)

### Remove PrevAssignedCost > 10,000,000

In [0]:
dataset[dataset['PrevAssignedCost'] >= 10000000]

             SKU        date  PrevAVGCost  ...  LatestDateCost  Type  GenPrice
25010  A-A-00032  2020-01-13         0.00  ...            0.00     A     51.00

[1 rows x 8 columns]

In [0]:
dataset.drop(dataset[dataset['PrevAssignedCost'] >= 10000000].index, inplace = True, axis = 0)
dataset.shape

(24627, 8)

### Remove GenPrice > 10,000,000

In [0]:
dataset[dataset['GenPrice'] >= 10000000]

             SKU        date  PrevAVGCost  ...  LatestDateCost  Type    GenPrice
24511  A-A-00032  2020-01-06        34.58  ...            0.00     A 12625006.00

[1 rows x 8 columns]

In [0]:
dataset.drop(dataset[dataset['GenPrice'] >= 10000000].index, inplace = True, axis = 0)
dataset.shape

(24626, 8)

## Calculate margin value

In [0]:
def calculateMargin(GenPrice, PrevAssignedCost, AVGCost):
  if PrevAssignedCost > 0.0:
      margin = ((GenPrice - PrevAssignedCost) / PrevAssignedCost) * 100.0
      if margin > 700.0:
          margin = ((GenPrice - AVGCost) / AVGCost) * 100.0
  else:
      margin = ((GenPrice - AVGCost) / AVGCost) * 100.0
  return margin

def calculateMargin(GenPrice, PrevAssignedCost, AVGCost):
  margin = 0
  if PrevAssignedCost > 0:
    margin = ((GenPrice - PrevAssignedCost) / PrevAssignedCost) * 100
  return margin

In [0]:
dataset['Margin'] = dataset.apply(lambda x: calculateMargin(x['GenPrice'], x['PrevAssignedCost'], x['AVGCost']), axis = 1)

In [0]:
dataset['Margin'].describe()

count   24626.00
mean       50.26
std        29.15
min       -59.41
25%        35.48
50%        45.71
75%        60.00
max      1900.00
Name: Margin, dtype: float64

In [0]:
dataset.head(10)

         SKU        date  PrevAVGCost  ...  Type  GenPrice  Margin
0  A-A-00001  2019-01-04        27.92  ...     A     41.00   24.24
1  A-B-00001  2019-01-04        57.33  ...     A     92.00   46.03
2  A-B-00002  2019-01-04        50.78  ...     A     76.00   40.74
3  A-C-00001  2019-01-04        45.75  ...     B     75.00   33.93
4  A-C-00019  2019-01-04        45.75  ...     B     75.00   33.93
5  A-C-00007  2019-01-04        59.37  ...     B     90.00   45.16
6  A-C-00002  2019-01-04        39.78  ...     B     68.00   51.11
7  A-C-00010  2019-01-04        61.22  ...     B     99.00   41.43
8  A-C-00003  2019-01-04        39.23  ...     B     64.00   48.84
9  A-C-00021  2019-01-04        48.82  ...     B     75.00   47.06

[10 rows x 9 columns]

In [0]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24626 entries, 0 to 25107
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SKU               24626 non-null  object
 1   date              24626 non-null  object
 2   PrevAVGCost       24626 non-null  float64
 3   PrevAssignedCost  24626 non-null  float64
 4   AVGCost           24626 non-null  float64
 5   LatestDateCost    24626 non-null  float64
 6   Type              24626 non-null  object
 7   GenPrice          24626 non-null  float64
 8   Margin            24626 non-null  float64
dtypes: float64(6), object(3)
memory usage: 1.9+ MB

## Create dummy variables for Types

In [0]:
TypedummyVar = pd.get_dummies(dataset['Type'])
TypedummyVar

       A  B  C  D  E  F  G
0      1  0  0  0  0  0  0
1      1  0  0  0  0  0  0
2      1  0  0  0  0  0  0
3      0  1  0  0  0  0  0
4      0  1  0  0  0  0  0
...   .. .. .. .. .. .. ..
25103  0  0  0  0  0  0  1
25104  0  0  0  0  0  0  1
25105  0  0  0  0  0  0  1
25106  0  0  0  0  0  0  1
25107  0  0  0  0  0  0  1

[24626 rows x 7 columns]

In [0]:
dataset2 = pd.concat([dataset[['PrevAVGCost', 'PrevAssignedCost', 'AVGCost', 'LatestDateCost', 'Type', 'GenPrice']], TypedummyVar], axis = 1)
dataset2

       PrevAVGCost  PrevAssignedCost  AVGCost  LatestDateCost  ...  D  E  F  G
0            27.92             33.00    28.55           20.54  ...  0  0  0  0
1            57.33             63.00    56.12           61.84  ...  0  0  0  0
2            50.78             54.00    45.13           50.00  ...  0  0  0  0
3            45.75             56.00    40.53           38.08  ...  0  0  0  0
4            45.75             56.00    40.53           38.08  ...  0  0  0  0
...            ...               ...      ...             ...  ... .. .. .. ..
25103         0.00             60.00     0.00            0.00  ...  0  0  0  1
25104        80.81             96.00     0.00            0.00  ...  0  0  0  1
25105         0.00             23.00    25.13           25.13  ...  0  0  0  1
25106       151.52            201.00   181.82          181.82  ...  0  0  0  1
25107         0.00             70.00     0.00            0.00  ...  0  0  0  1

[24626 rows x 13 columns]

## Extract MainCat and SubCat from SKU

In [0]:
dataset2['Cat'] = dataset['SKU'].apply(lambda x : x[0])
dataset2

       PrevAVGCost  PrevAssignedCost  AVGCost  LatestDateCost  ...  E  F  G  Cat
0            27.92             33.00    28.55           20.54  ...  0  0  0    A
1            57.33             63.00    56.12           61.84  ...  0  0  0    A
2            50.78             54.00    45.13           50.00  ...  0  0  0    A
3            45.75             56.00    40.53           38.08  ...  0  0  0    A
4            45.75             56.00    40.53           38.08  ...  0  0  0    A
...            ...               ...      ...             ...  ... .. .. ..  ...
25103         0.00             60.00     0.00            0.00  ...  0  0  1    E
25104        80.81             96.00     0.00            0.00  ...  0  0  1    E
25105         0.00             23.00    25.13           25.13  ...  0  0  1    E
25106       151.52            201.00   181.82          181.82  ...  0  0  1    E
25107         0.00             70.00     0.00            0.00  ...  0  0  1    E

[24626 rows x 14 columns]

In [0]:
dataset2['Cat'].unique()

array(['A', 'E'], dtype=object)

In [0]:
dataset2['SubCat'] = dataset['SKU'].apply(lambda x : x[2])
dataset2

       PrevAVGCost  PrevAssignedCost  AVGCost  LatestDateCost  ...  F  G  Cat  SubCat
0            27.92             33.00    28.55           20.54  ...  0  0    A       A
1            57.33             63.00    56.12           61.84  ...  0  0    A       B
2            50.78             54.00    45.13           50.00  ...  0  0    A       B
3            45.75             56.00    40.53           38.08  ...  0  0    A       C
4            45.75             56.00    40.53           38.08  ...  0  0    A       C
...            ...               ...      ...             ...  ... .. ..  ...     ...
25103         0.00             60.00     0.00            0.00  ...  0  1    E       E
25104        80.81             96.00     0.00            0.00  ...  0  1    E       A
25105         0.00             23.00    25.13           25.13  ...  0  1    E       A
25106       151.52            201.00   181.82          181.82  ...  0  1    E       E
25107         0.00             70.00     0.00            0.00  ...  0  1    E       A

[24626 rows x 15 columns]

### Create dummy variables for Category and Subcategory

In [0]:
categoryDummy = pd.get_dummies(dataset2['Cat'])
categoryDummy.rename(columns = {'A':'Cat A', 'E':'Cat E'}, inplace = True)
dataset2 = pd.concat([dataset2, categoryDummy], axis = 1)
dataset2

       PrevAVGCost  PrevAssignedCost  AVGCost  ...  SubCat Cat A  Cat E
0            27.92             33.00    28.55  ...       A     1      0
1            57.33             63.00    56.12  ...       B     1      0
2            50.78             54.00    45.13  ...       B     1      0
3            45.75             56.00    40.53  ...       C     1      0
4            45.75             56.00    40.53  ...       C     1      0
...            ...               ...      ...  ...     ...   ...    ...
25103         0.00             60.00     0.00  ...       E     0      1
25104        80.81             96.00     0.00  ...       A     0      1
25105         0.00             23.00    25.13  ...       A     0      1
25106       151.52            201.00   181.82  ...       E     0      1
25107         0.00             70.00     0.00  ...       A     0      1

[24626 rows x 17 columns]

In [0]:
subCategoryDummy = pd.get_dummies(dataset2['SubCat'])
subCategoryDummy.rename(columns = {'A':'SubCat A', 'B':'SubCat B', 'C':'SubCat C', 'D':'SubCat D', 'E':'SubCat E', 'F':'SubCat F', 'G':'SubCat G', 'H':'SubCat H', 'I':'SubCat I', 'J':'SubCat J', 'K':'SubCat K'}, inplace = True)
dataset2 = pd.concat([dataset2, subCategoryDummy], axis = 1)
dataset2

       PrevAVGCost  PrevAssignedCost  AVGCost  ...  SubCat I SubCat J  SubCat K
0            27.92             33.00    28.55  ...         0        0         0
1            57.33             63.00    56.12  ...         0        0         0
2            50.78             54.00    45.13  ...         0        0         0
3            45.75             56.00    40.53  ...         0        0         0
4            45.75             56.00    40.53  ...         0        0         0
...            ...               ...      ...  ...       ...      ...       ...
25103         0.00             60.00     0.00  ...         0        0         0
25104        80.81             96.00     0.00  ...         0        0         0
25105         0.00             23.00    25.13  ...         0        0         0
25106       151.52            201.00   181.82  ...         0        0         0
25107         0.00             70.00     0.00  ...         0        0         0

[24626 rows x 28 columns]

## Extract Year from date

In [0]:
dataset2['Year'] = pd.DatetimeIndex(dataset['date']).year

In [0]:
from pandas.api.types import CategoricalDtype
year_bucket2019 = ['1', '0']
dataset2['Year19'] = pd.cut(dataset2.Year,
                                      bins = [2019, 2020, np.inf],
                                      labels = year_bucket2019,
                                      right = False).astype(str).astype(CategoricalDtype(year_bucket2019, ordered = True))

In [0]:
year_bucket2020 = ['0', '1']
dataset2['Year20'] = pd.cut(dataset2.Year,
                                      bins = [2019, 2020, np.inf],
                                      labels = year_bucket2020,
                                      right = False).astype(str).astype(CategoricalDtype(year_bucket2020, ordered = True))

## Delete unused columns

In [0]:
dataset3 = dataset2.drop(['Type', 'Year', 'Cat', 'SubCat'], axis=1)
dataset3

       PrevAVGCost  PrevAssignedCost  AVGCost  ...  SubCat K  Year19  Year20
0            27.92             33.00    28.55  ...         0       1       0
1            57.33             63.00    56.12  ...         0       1       0
2            50.78             54.00    45.13  ...         0       1       0
3            45.75             56.00    40.53  ...         0       1       0
4            45.75             56.00    40.53  ...         0       1       0
...            ...               ...      ...  ...       ...     ...     ...
25103         0.00             60.00     0.00  ...         0       0       1
25104        80.81             96.00     0.00  ...         0       0       1
25105         0.00             23.00    25.13  ...         0       0       1
25106       151.52            201.00   181.82  ...         0       0       1
25107         0.00             70.00     0.00  ...         0       0       1

[24626 rows x 27 columns]

In [0]:
dataset3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24626 entries, 0 to 25107
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PrevAVGCost       24626 non-null  float64
 1   PrevAssignedCost  24626 non-null  float64
 2   AVGCost           24626 non-null  float64
 3   LatestDateCost    24626 non-null  float64
 4   GenPrice          24626 non-null  float64
 5   A                 24626 non-null  uint8
 6   B                 24626 non-null  uint8
 7   C                 24626 non-null  uint8
 8   D                 24626 non-null  uint8
 9   E                 24626 non-null  uint8
 10  F                 24626 non-null  uint8
 11  G                 24626 non-null  uint8
 12  Cat A             24626 non-null  uint8
 13  Cat E             24626 non-null  uint8
 14  SubCat A          24626 non-null  uint8
 15  SubCat B          24626 non-null  uint8
 16  SubCat C          24626 non-null  uint8
 17  SubCat D          24626 non-null  uint8
 18  SubCat E          24626 non-null  uint8
 19  SubCat F          24626 non-null  uint8
 20  SubCat G          24626 non-null  uint8
 21  SubCat H          24626 non-null  uint8
 22  SubCat I          24626 non-null  uint8
 23  SubCat J          24626 non-null  uint8
 24  SubCat K          24626 non-null  uint8
 25  Year19            24626 non-null  category
 26  Year20            24626 non-null  category
dtypes: category(2), float64(5), uint8(20)
memory usage: 1.6 MB

## Exporting the cleaned dataset

In [0]:
dataset3.to_csv('cleanData_Final.csv')